### ISSUE TITLE
hw 95 feedback

### ISSUE THREAD

**Issue by jwu01** [michaellikaiye/lush-liquid#2]
## recursive abstraction
"one step away" can be more specific. IAway is kinda vague. 

## base case
Is the wall not part of the base case?

## pseudocode
The algorithm looks pretty good

**Comment by michaellikaiye** [comment]
fixed recursive abstraction so next step is not so vague

the wall is not part of the base case, it is what you reject
(in wiki's terms: reject(P,c))

**Comment by michaellikaiye** [comment]
Thank you for the help Jeffery and Rachel!
